export default {
  config: {
    locales: ["ru"],
    translations: {
      ru: {
        // ===== ГЛОБАЛЬНЫЕ ЭЛЕМЕНТЫ =====
        "global.home": "Главная",
        "global.back": "Назад",
        "global.cancel": "Отмена",
        "global.close": "Закрыть",
        "global.continue": "Продолжить",
        "global.delete": "Удалить",
        "global.description": "Описание",
        "global.details": "Детали",
        "global.disabled": "Отключено",
        "global.documentation": "Документация",
        "global.enabled": "Включено",
        "global.error": "Произошла ошибка",
        "global.finish": "Завершить",
        "global.marketplace": "Маркетплейс",
        "global.more": "Ещё",
        "global.name": "Название",
        "global.new": "Новый",
        "global.none": "Нет",
        "global.password": "Пароль",
        "global.permissions": "Разрешения",
        "global.plugins": "Плагины",
        "global.profile": "Профиль",
        "global.publish": "Опубликовать",
        "global.reset": "Сбросить",
        "global.roles": "Роли",
        "global.save": "Сохранить",
        "global.search": "Поиск",
        "global.see-more": "Показать ещё",
        "global.select": "Выбрать",
        "global.select-all": "Выбрать все",
        "global.settings": "Настройки",
        "global.type": "Тип",
        "global.users": "Пользователи",
        "global.change-password": "Сменить пароль",
        "global.content-manager": "Редактор контента",
        "global.actions": "Действия",
        
        // ===== ПЛАГИНЫ В МЕНЮ =====
        "global.plugins.content-manager": "Редактор контента",
        "global.plugins.content-type-builder": "Конструктор типов",
        "global.plugins.documentation": "Документация",
        "global.plugins.upload": "Медиатека",
        "global.plugins.i18n": "Интернационализация",
        
        // ===== ГЛАВНАЯ СТРАНИЦА =====
        "HomePage.head.title": "Главная",
        "HomePage.header.title": "Привет {name}",
        "HomePage.header.subtitle": "Добро пожаловать в панель администратора",
        "HomePage.widget.loading": "Загрузка виджета...",
        "HomePage.widget.error": "Не удалось загрузить виджет.",
        "HomePage.widget.no-data": "Контент не найден.",
        "HomePage.widget.no-permissions": "Нет прав для просмотра",
        "HomePage.addWidget.title": "Добавить виджет",
        "HomePage.addWidget.button": "Добавить виджет",
        "HomePage.addWidget.noWidgetsAvailable": "Нет доступных виджетов",
        "HomePage.widget.delete": "Удалить",
        "HomePage.widget.drag": "Перетащить",
        
        // ===== ВИДЖЕТЫ CONTENT-MANAGER (с префиксом) =====
        "content-manager.widget.chart-entries.title": "Записи",
        "content-manager.widget.chart-entries.count.label": "{count, plural, =0 {Записей} one {Запись} few {Записи} other {Записей}}",
        "content-manager.widget.chart-entries.tooltip": "{count} {label}",
        "content-manager.widget.last-edited.title": "Последние изменённые",
        "content-manager.widget.last-edited.single-type": "Единичный тип",
        "content-manager.widget.last-edited.no-data": "Нет изменённых записей",
        "content-manager.widget.last-published.title": "Последние опубликованные",
        "content-manager.widget.last-published.no-data": "Нет опубликованных записей",
        "content-manager.actions.edit.label": "Редактировать",
        
        // ===== ДЕЙСТВИЯ =====
        "Publish": "Опубликовать",
        "Unpublish": "Снять с публикации",
        "Save": "Сохранить",
        "Cancel": "Отмена",
        "Delete": "Удалить",
        "Confirm": "Подтвердить",
        "Create": "Создать",
        "Add": "Добавить",
        "Edit": "Редактировать",
        "Apply": "Применить",
        "Clear": "Очистить",
        "Copy": "Копировать",
        "Duplicate": "Дублировать",
        "Back": "Назад",
        "Add Widget": "Добавить виджет",
        
        // ===== СТАТУСЫ =====
        "published": "Опубликовано",
        "draft": "Черновик",
        "modified": "Изменено",
        "Status": "Статус",
        
        // ===== ТИПЫ КОНТЕНТА =====
        "Product": "Товар",
        "Faq": "FAQ",
        "Banner": "Баннер",
        "Review": "Отзыв",
        "Video": "Видео",
        
        // ===== ПОЛЬЗОВАТЕЛИ =====
        "Users": "Пользователи",
        "Roles": "Роли",
        "Providers": "Провайдеры",
        "Email templates": "Шаблоны email",
        "Advanced settings": "Расширенные настройки",
        "Active": "Активен",
        "Blocked": "Заблокирован",
        
        // ===== ПРОФИЛЬ =====
        "Profile": "Профиль",
        "Profile settings": "Настройки профиля",
        "First name": "Имя",
        "Last name": "Фамилия",
        "Username": "Логин",
        "Email": "Email",
        "Password": "Пароль",
        "Current Password": "Текущий пароль",
        "Confirm Password": "Подтверждение пароля",
        "Change password": "Сменить пароль",
        "Experience": "Интерфейс",
        "Interface language": "Язык интерфейса",
        "Logout": "Выйти",
        
        // ===== СТАТИСТИКА =====
        "Entries": "Записи",
        "Assets": "Ассеты",
        "Content-Types": "Типы контента",
        "Components": "Компоненты",
        "Locales": "Локали",
        "Admins": "Администраторы",
        "Webhooks": "Вебхуки",
        "API Tokens": "API токены",
        "Project statistics": "Статистика проекта",
        
        // ===== ДОПОЛНИТЕЛЬНО =====
        "Loading...": "Загрузка...",
        "No data": "Нет данных",
        "Empty": "Пусто",
        "Close": "Закрыть",
        "Open": "Открыть",
        "More": "Ещё",
        "Less": "Меньше",
        "All": "Все",
        "None": "Нет",
        "Yes": "Да",
        "No": "Нет",
        "Show": "Показать",
        "Hide": "Скрыть",
        "Optional": "Необязательно",
        "Required": "Обязательно",
        
        // ===== ФОРМЫ =====
        "Name": "Название",
        "Title": "Заголовок",
        "Description": "Описание",
        "Type": "Тип",
        "Value": "Значение",
        "Default": "По умолчанию",
        "Text": "Текст",
        "Number": "Число",
        "Boolean": "Да/Нет",
        "Date": "Дата",
        "DateTime": "Дата и время",
        "Time": "Время",
        "JSON": "JSON",
        "Media": "Медиа",
        
        // ===== РОЛИ АДМИНОВ =====
        "Super Admin": "Супер-админ",
        "Editor": "Редактор",
        "Author": "Автор",
        
        // ===== МЕДИАТЕКА =====
        "Browse": "Обзор",
        "Upload": "Загрузить",
        "Folders": "Папки",
        "File": "Файл",
        "Files": "Файлы",
        "Image": "Изображение",
        "Video": "Видео",
        "Audio": "Аудио",
        "Document": "Документ",
        
        // ===== КОНСТРУКТОР ТИПОВ =====
        "Collection Types": "Типы коллекций",
        "Single Types": "Единичные типы",
        "Display name": "Отображаемое имя",
        
        // ===== НАВИГАЦИЯ =====
        "Content Manager": "Редактор контента",
        "Content Type Builder": "Конструктор типов",
        "Media Library": "Медиатека",
        
        // ===== АВТОРИЗАЦИЯ =====
        "Auth.form.welcome.title": "Добро пожаловать!",
        "Auth.form.welcome.subtitle": "Войдите в аккаунт",
        "Auth.form.email.label": "Email",
        "Auth.form.password.label": "Пароль",
        "Auth.form.button.login": "Войти",
        "Auth.form.rememberMe.label": "Запомнить меня",
        "Auth.link.forgot-password": "Забыли пароль?",
        
        // ===== НАСТРОЙКИ =====
        "Settings.PageTitle": "Настройки — {name}",
        "Settings.apiTokens.title": "API Токены",
        "Global Settings": "Глобальные настройки",
        "Administration Panel": "Админ-панель",
        "Overview": "Обзор",
        "Application": "Приложение",
        "Configuration": "Конфигурация",
        "Internationalization": "Интернационализация",
        
        // ===== ПОДТВЕРЖДЕНИЯ =====
        "Are you sure?": "Вы уверены?",
        "This action cannot be undone.": "Это действие нельзя отменить.",
        
        // ===== ЕЩЁ НУЖНЫЕ КЛЮЧИ =====
        "app.components.LeftMenu.logout": "Выйти",
        "app.utils.edit": "Редактировать",
        "components.PageFooter.select": "Записей на странице",
      },
    },
  },
  bootstrap() {},
};
